version: '3.1'
services:
  db:
    image: mysql:5.7.21
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data: